name: Lintian-brush

on: push
    
jobs:
  lintian-brush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run lintian-brush
        uses: gizmoguy/action-lintian-brush@v1
        with:
          no_update_changelog: true
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: lintian-brush
          title: 'Update debian packaging'
          body: |
            Automated changes by [lintian-brush][1]

            [1]: https://salsa.debian.org/jelmer/lintian-brush
