name: Renovate

on: push
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: gizmoguy/action-lintian-brush@v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
